name: Snake contribution animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: SmokeyBear10
          outputs: |
            snk/github-contribution-grid-snake.svg?color_snake=%23ff79c6&color_dots=%23282a36,%2344475a,%236272a4,%23bd93f9,%23ff79c6
            snk/github-contribution-grid-snake-dark.svg?color_snake=%23ff79c6&color_dots=%23282a36,%2344475a,%236272a4,%23bd93f9,%23ff79c6

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add snk
          git diff --cached --quiet || git commit -m "chore: update snake animation"
          git push
